//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ID { get; set; }
        public string Name_Client { get; set; }
        public int Doctor_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public int Clinic_ID { get; set; }
        public System.DateTime Time { get; set; }
        public string Status { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
    }
}
