//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOfClinic
    {
        public int EmployeeID { get; set; }
        public int ClinicID { get; set; }
        public Nullable<System.TimeSpan> Time_begin { get; set; }
        public Nullable<System.TimeSpan> Time_end { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
